galaxy_info:
  author: Guillaume Charbonnier
  description: Install SystemD timers

  license: MIT
  min_ansible_version: "2.2"

  platforms:
    - name: Ubuntu
      versions:
        - xenial
        - bionic
        - focal
        - jammy

  galaxy_tags:
    - systemd
    - timers

dependencies: []
